name = "lapce-angular"
version = "0.1.0"
author = "Stanislav Lapata"
display-name = "Angular"
description = "Angular plugin for the Lapce Editor - Powered by angular"
wasm = "bin/lapce-angular.wasm"
repository = "https://github.com/Stanislav-Lapata/lapce-angular"
icon = "assets/angular.svg"

[activation]
language = ["typescript", "html"]
workspace-contains = ["*/angular.json"]

[config.serverPath]
default = "ngserver"
description = "Path to the ngserver command."

[config.serverArgs]
default = ["--stdio", "--tsProbeLocations", "", "--ngProbeLocations", ""]
description = "LSP server arguments to pass when launching."
